[build]
  command = "npm run build"
  functions = "netlify/functions"
  publish = "dist"

[build.environment]
  NODE_VERSION = "19.9.0"
  NPM_VERSION = "9.6.3"


[dev]
  command = "npm run dev"
  functions = "netlify/functions"
  publish = "dist"

[functions]
  node_bundler = "esbuild"
  external_node_modules = [
    "googleapis",
    "google-auth-library",
    "nodemailer"
  ]
