[build]
  command = "npm run build"
  publish = "out"

[[headers]]
  for = "/*"
  [headers.values]
   # Load scripts only via HTTPS and from allowed domains.
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "origin-when-cross-origin"
    X-Content-Type-Options = "nosniff"
    X-DNS-Prefetch-Control = "on"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
    Permissions-Policy = "camera=(), microphone=(), geolocation=(), interest-cohort=()"

[context.branch-deploy]
  command = "npm run build"
  publish = "out"

[dev]
  command = "npm run dev" # Command to start your dev server
  port = 8888 # The port that the netlify dev will be accessible on
  autoLaunch = true # a Boolean value that determines if Netlify Dev launches the local server address in your browser
